baseURL = "https://hiurequeiroz.github.io/"
defaultContentLanguage = "en"
languageCode = "en"
title = "Hiure Queiroz"
theme = "gokarna"
enableRobotsTXT = true
pygmentsStyle = "monokai"

[params]
  footer = "Hiure"
  description = "Developer / Researcher / Physicist"
  avatarURL = "/images/perfil.png"
  AvatarAltText = "avatar"
  avatarSize = "size-xl"
  ShowBackToTopButton = true # true or false for "back to top" button on posts
  togglePreviousAndNextButtons = "true"
  customHeadHTML = """
    <!-- KaTeX -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.css" integrity="sha384-Xi8rHCmBmhbuyyhbI88391ZKP2dmfnOl4rT9ZfRI7mLTdk1wblIUnrIq35nqwEvC" crossorigin="anonymous">
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/katex.min.js" integrity="sha384-X/XCfMm41VSsqRNQgDerQczD69XqmjOOOwYQvr/uuC+j4OPoNhVgjdGFwhvN02Ja" crossorigin="anonymous"></script>
    <script defer src="https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/auto-render.min.js" integrity="sha384-+XBljXPPiv+OzfbB3cVmLHf4hdUFHlWNZN5spNQ7rmHTXpd7WvJum6fIACpNNfIR" crossorigin="anonymous"></script>
    <script>
      document.addEventListener("DOMContentLoaded", function() {
        renderMathInElement(document.body, {
          // customised options
          // • auto-render specific keys, e.g.:
          delimiters: [
            {left: '$$', right: '$$', display: true},
            {left: '$', right: '$', display: false},
          ],
          // • rendering keys, e.g.:
          throwOnError : false
        });
      });
    </script>
  """
  MainProject = "Community Networks"
  projectIMG = "/images/communitynetworks.png"
  ProjectAltTxt = "working with communities"
  ProjectImgSize = "size-xl"
  ProjectDescription = "For more self-governing networks and more humane communications infrastructures"
  VideoEmbeded = "https://www.youtube.com/embed"
  ProjectVIDEO = [
    {name = "BambuTower", id = "KRib7hyTWMw"},
    {name = "DwebCamp", id = "vb9GYb1j85k"},
    {name = "CoolabCamp", id = "P6YDu3nKNvQ"}
    ]
  showPostsOnHomePage = "recent"
[[params.developmentProjects]]
  name = "Guia de Redes Comunitárias - Digital Democracy"
  featureImage = "/images/manuais.png"
  technologies = "Roteadores, Redes Comunitárias, Governança Comunitária"
  description = "Tenho me dedicado a escrever manuais ao longo do tempo para consolidar todo o conhecimento adquirido com os trabalhos em comunidades. O manual mais recente aborda uma tecnologia social de organização comunitária para gerenciar redes de comunicação comunitárias. Ele fornece orientações sobre como escolher o tipo de rede mais adequado ao seu cenário, além de discutir a governança de comunidades."
  challenges = "O maior desafio neste trabalho foi utilizar termos muito simples para abordar temas incomuns para a maioria das comunidades"
  results = "O resultado foi um belo manual publicado dentro do Earth Defender Tool Kit pela Digital Democracy"
  codeLink = "https://www.earthdefenderstoolkit.com/wp-content/uploads/2024/02/Guide-Community-Networks-3-PT-BR.pdf"
  liveLink = "https://www.earthdefenderstoolkit.com/toolkit/guide-community-networks/"

[[params.developmentProjects]]
  name = "Projeto Dev 2"
  featureImage = "/path/to/image2.jpg"
  technologies = "Python, Flask"
  description = "Descrição do Projeto Dev 2"
  challenges = "Desafios do Projeto Dev 2"
  results = "Resultados do Projeto Dev 2"
  codeLink = "https://github.com/exemplo/projeto-dev2"
  liveLink = "https://exemplo.com/projeto-dev2"

[[params.communityProjects]]
  name = "Projeto Comunitário 1"
  featureImage = "/path/to/image3.jpg"
  technologies = "React, Node.js"
  description = "Descrição do Projeto Comunitário 1"
  challenges = "Desafios do Projeto Comunitário 1"
  results = "Resultados do Projeto Comunitário 1"
  codeLink = "https://github.com/exemplo/projeto-com1"
  liveLink = "https://exemplo.com/projeto-com1"
[menu]
  [[menu.main]]
    name = "About"
    pre = "<span data-feather='meh'></span>"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    pre = "<span data-feather='book'></span>"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    pre = "<span data-feather='code'></span>"
    url = "/projects/"
    weight = 3

  [[menu.main]]
    name = "Tags"
    pre = "<span data-feather='tag'></span>"
    url = "/tags/"
    weight = 4
    
  [[menu.main]]
    identifier = "github"
    url = "https://github.com/hiurequeiroz"
    weight = 5
    # We use feather-icons: https://feathericons.com/
    pre = "<span data-feather='github'></span>"


defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
[languages]
  [languages.pt]
    contentDir = 'content/pt'
    disabled = false
    languageCode = 'pt-BR'
    languageDirection = 'ltr'
    languageName = 'Portuguese'
    weight = 2
    [languages.pt.params]
      subtitle = 'Referências, Tutoriais e Explicações'
  [languages.en]
    contentDir = 'content/en'
    disabled = false
    languageCode = 'en-US'
    languageDirection = 'ltr'
    languageName = 'English'
    weight = 1
    [languages.en.params]
      subtitle = 'Reference, Tutorials, and Explanations'



[services]
  [services.disqus]
    shortname = 'hiurequeiroz-github-io'
